name: Snyk CICD
run-name: ${{ github.actor }} is running Snyk on ${{ github.repository }} repository.

on:
  pull_request:
    branches:  [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check Terraform files for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} ## requires snyk api token within repo secrets
        with:
          args: --scan=resource-changes
